[package]
name = "laminations-lib-rs"
version = "0.1.0"
authors = ["Caleb Falcione <caleb.falcione@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.3"